version: '2'
services:
  db:
    image: mysql:5.7
    volumes:
      - '/Users/sadikay/Documents/dbdata:/var/lib/mysql'
    restart: always
    environment:
     MYSQL_ROOT_PASSWORD: '12341234'
     MYSQL_DATABASE: notification_dashboard_development
     MYSQL_USER: notification_user
     MYSQL_PASSWORD: 12341234
    ports:
      - '3306:3306'

  redis:
      image: redis:alpine
      environment:
        # ALLOW_EMPTY_PASSWORD is recommended only for development.
        - ALLOW_EMPTY_PASSWORD=yes
      ports:
        - '6379'

  web:
    command: "/go-api-worker/main"
    ports:
      - "8080:8080"
    depends_on:
      - 'db'
      - 'redis'
    image: notification-center/go-worker-api
    build: ./go-api-worker
    # environment:
    #   VIRTUAL_HOST: yourdomain.com
    links:
      - redis:redis
      - db

volumes:
  'dbdata':
