version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  # whoami:
  #   image: jwilder/whoami
  #   container_name: whoami
  #   environment:
  #     - VIRTUAL_HOST=whoami.local

  db:
    image: mysql:5.7
    volumes:
      - '/Users/sadikay/Documents/dbdata:/var/lib/mysql'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpasswd
      - MYSQL_DATABASE=notification_center_prod
      - MYSQL_USER=nc_db_user
      - MYSQL_PASSWORD=nc_db_user_pwd
    ports:
      - '3306:3306'
    # healthcheck:
    #   test: ["CMD", "mysql", "-u", "root", "-e", "select 1"]


  redis:
    image: redis:alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379'
    # healthcheck:
    #   test: ["CMD", "redis-cli", "ping"]

  web:
    ports:
      - "3000:3000"
    depends_on:
      - 'db'
      - 'redis'
    build: ./rails-dashboard
    environment:
      SECRET_KEY_BASE: CHANGE_ME=yourSecureSercretKeyBase2ndi2nrfiaskd3r94nr
      DB_PRODUCTION_USERNAME: nc_db_user
      DB_PRODUCTION_PASSWORD: nc_db_user_pwd
      DB_PRODUCTION_HOST: db

  api:
    command: "/go-api-worker/main"
    ports:
      - "8080:8080"
    # depends_on:
    #   - 'db'
    #   - 'redis'
    # image: notification-center/go-worker-api
    build: ./go-api-worker
    environment:
      - GIN_MODE=release
    links:
      - redis:redis
      - db

volumes:
  'dbdata':
