version: '2.1'
services:
  db:
    image: mysql:5.7
    volumes:
      - '/Users/sadikay/Documents/dbdata:/var/lib/mysql'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=notification_center_prod
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    healthcheck:
      test: "/etc/init.d/mysql status"
      timeout: 16s
      interval: 5s


  redis:
    image: redis:alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379'

  web:
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    build: ./rails-dashboard
    environment:
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      DB_PRODUCTION_USERNAME: ${MYSQL_USER}
      DB_PRODUCTION_PASSWORD: ${MYSQL_PASSWORD}
      DB_PRODUCTION_HOST: db

  api:
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    # image: notification-center/go-worker-api
    build: ./go-api-worker
    environment:
      - GIN_MODE=release
      - DB_PRODUCTION_USERNAME=${MYSQL_USER}
      - DB_PRODUCTION_PASSWORD=${MYSQL_PASSWORD}
    links:
      - redis:redis
      - db

volumes:
  'dbdata':
