# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 921aad7c9aa36091a9fd4e1a95b0abb9d9d004feeb95f7652302d6af15f03027a26ee831411be0a0d5b65e40d45ce9fc6411e0a22f3897011caa7961bf553de4

test:
  secret_key_base: 502d82bc855721c654e339014143b8359f63c2c5681b96d950b478650c4f8143aafe95004090b82006ccf62f4b0bd30b3d892dc7103c503aa76b4a23ed1a532f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: 502d82bc855721c654e339014143b8359f63c2c5681b96d950b478650c4f8143aafe95004090b82006ccf62f4b0bd30b3d892dc7103c503aa76b4a23ed1a532f
