---
:verbose: false
:pidfile: ./tmp/pids/sidekiq.pid
:concurrency:  25
:timeout: 10

production:
  :concurrency: 30

:limits:
  low_priority: 10
  critical: 15

process_limits:
  test: 1

:queues:
  - [high_priority, 1]
  - [critical, 2]
  - [mailer, 3]
  - [low_priority, 30]
  - [default, 100]

:ignore_queues:
  - [no_ignore, 10]

:schedule:
  activity_scheduler_job:
    cron: '0 * * * * *'   # Runs once per minute
    class: ActivitySchedulerJob
:retry:
  - [mailer, 0]
